apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: ack-acmpca-writer
rules:
- apiGroups:
  - acmpca.services.k8s.aws
  resources:
  - certificates
  - certificateauthorities
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - acmpca.services.k8s.aws
  resources:
  - certificates
  - certificateauthorities
  verbs:
  - get
  - patch
  - update
