apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: metallb-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: metallb-manager-role
subjects:
- kind: ServiceAccount
  name: manager-account
  namespace: metallb-system
