apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    containerImage: ghcr.io/snapp-incubator/ceph-s3-operator:v0.3.6
    alm-examples: |-
      [
        {
          "apiVersion": "s3.snappcloud.io/v1alpha1",
          "kind": "S3Bucket",
          "metadata": {
            "name": "s3bucket-sample",
            "namespace": "ceph-s3-operator-test"
          },
          "spec": {
            "s3DeletionPolicy": "delete",
            "s3SubuserBinding": [
              {
                "access": "write",
                "name": "subuser1"
              },
              {
                "access": "read",
                "name": "subuser2"
              }
            ],
            "s3UserRef": "s3userclaim-sample"
          }
        },
        {
          "apiVersion": "s3.snappcloud.io/v1alpha1",
          "kind": "S3User",
          "metadata": {
            "name": "s3user-sample"
          },
          "spec": null
        },
        {
          "apiVersion": "s3.snappcloud.io/v1alpha1",
          "kind": "S3UserClaim",
          "metadata": {
            "name": "s3userclaim-sample",
            "namespace": "ceph-s3-operator-test"
          },
          "spec": {
            "adminSecret": "s3-sample-admin-secret",
            "quota": {
              "maxBuckets": 5,
              "maxObjects": 1000,
              "maxSize": 1000
            },
            "readonlySecret": "s3-sample-readonly-secret",
            "s3UserClass": "ceph-default",
            "subusers": [
              "subuser1",
              "subuser2"
            ]
          }
        }
      ]
    capabilities: Basic Install
    categories: Storage
    createdAt: "2024-01-19T19:24:22Z"
    description: Provision and manage users and buckets in S3 object storage created
      with Ceph RGW on Kubernetes and OpenShift.
    operators.operatorframework.io/builder: operator-sdk-v1.31.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
    repository: https://github.com/snapp-incubator/ceph-s3-operator
    support: Snappcloud
  name: ceph-s3-operator.v0.3.6
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: S3 Bucket Instance
      displayName: S3 Bucket
      kind: S3Bucket
      name: s3buckets.s3.snappcloud.io
      version: v1alpha1
    - description: S3 User Claim Instance
      displayName: S3 User Claim
      kind: S3UserClaim
      name: s3userclaims.s3.snappcloud.io
      version: v1alpha1
    - description: S3 User is created by the S3 User Claim instance. It's not applicable
        for the operator user.
      displayName: S3 User
      kind: S3User
      name: s3users.s3.snappcloud.io
      version: v1alpha1
  description: |
    The Ceph S3 Operator, an open-source endeavor, is crafted to streamline the management of S3 users and buckets within a Ceph cluster environment. It enhances efficiency and simplifies processes, rendering S3 usage on Ceph clusters more straightforward and user-friendly.

    ## Features

    - S3 User Management
    - Bucket Management
    - Subuser Support
    - Bucket policy Support
    - Quota Management
    - Webhook Integration
    - E2E Testing
    - Helm Chart and OLM Support

    ## Usage and Documentation

    - CRD Examples: Located in the [samples](https://github.com/snapp-incubator/ceph-s3-operator/tree/main/config/samples) folder.
    - Detailed Documentation: Available on the [wiki](https://github.com/snapp-incubator/ceph-s3-operator/wiki).
    - Design and Decision Insights: Refer to our [design doc](https://github.com/snapp-incubator/ceph-s3-operator/blob/main/docs/DESIGN.md) for an in-depth understanding.
  displayName: Ceph S3 Operator
  icon:
  - base64data: iVBORw0KGgoAAAANSUhEUgAAAFAAAAAoCAMAAABevo0zAAABaFBMVEVHcEwBBikABTMAABsAACAAACQAAifr//8BCCwCCi7q/v79//8CEzz////n+/v7///p/fwACzgACTYDFz8NGTgAABUJDzAADToTKkYjR18WMEvu//81bnny//8LIEYAAC5u7ddOpqL4//8AAA9cv7VHkZMqMExo28orXW1s4tAoVGViy78RJkJt69XK9PI+gIaOo6/a//8cPlUUHj17/+fY6uwWLFAZNlAMFDS80dZBiIza4eQxZXJv8NoeJEFNUWdl18dsf5OousQ5P1gEDTE6eYFjd4vt7++6xMuQlKHf//9Xs6xWW3F/kaJlaHxTraearLiPp7JPYnvi9vYhNlhW18tKnJtIWnV8gZE7SWacn6tj0cPW1toAASmwxMxQz8JbbYVv5dLNztPQ+Pa/6+pMs69e4NHK3OBxdYdWaoBftbCSsLiwsrtex7o2dH2Km6t19t6np7NZl510ipx5traV6eCU2NSi6eKkA5MiAAAAAXRSTlMAQObYZgAABRJJREFUSMell2dX20gUhiPNaJCEiiVZlnuRe8PGvYGbwDY2hoXQe01CS0/+/o4gm91z9sPK7P2ic1we335fv3nzb5v72wRWn2ff9da7q6tf86dlfd4n2P7x9htr9vvzNlb3DbsuvyQHTgKSxFX28mXRJ7CvBQo+3+aBFgjIiuTKJThFIQOk//yd6BFeBWRtYv1A0pSKN2okQqnd6Eku6lJIWelu68IrgDaPvq6Q2knrotSgOzmXPV51lZIRL6eRb+vir7BnANo87BYpuxuOYnoj44x/enImW0Q0XWqAqiJzedHGzga0eYQDUkqlSzlgR8ge96bsRy6KsifowsWuX5PWRdtMQHbOtydLrWQ25CQIhlJbd61xFFDGCYSpZDZS1eSPojALUBBXScl7kcxRFEPD6b7q9BbCkwlgDAa6I9l0VeNOzcpYBQp6T5ISF0kvoBmKmPJr9/1i7Oui3kYUw1D2u+CjU6pse1irQNaz/VaudrI5gL8ea+pXC4uLV4trC9v65TIyiZHgBkee46AtAgVxneRCSyGKphlwOHe98Muurn37wMBOuztZr6zUfTaLQM92hUxkOxmcPwOusosvtoaN3YIGjV/0ZtNO8oMuWASKm6QyXlqBDM0gAFbv8/k/TMvn7z+oADE0RkaCK6S/7LMI1PcCruRREacLLk8nlAqhGlbDYQjDxHRaNH8HtoIRhcyLFoHlCtlY2sUFhW1e5AcxRMU+Xz70EdUX+Xmxj4moeJR0BbZ0i8Aex92VEpBBjsEDYT8eUH1+7ef3n33H/NBBDAcErhUVKq0E3m5bBK5LXCaBI4Z9Pgbh8iB2fHV2drYTOmg6IDjgl7HvqOCqcf53FoFdycjQuGdQkX8fphlj+fqo0Cjc7LgJAsHiFHuIs2i3a8qpReBqoLC0gcxvjfj9GlTtZ2et3cTNjlOFxRgKmzzKHYxwXM8qkKymoyaQUPd5/vSLM3p7u3O7E8p8qc/zgzYuCo0y6V3rQBwyBZAZ8mGtNs1/q7p2bnZuzp7sd/lJ7MHMIXaeOuGUoUXgR4lzNTLIwF2zDCEIo7Q3tdQo3LrDAEJKf2+OeGrFqVkuyinHRXDbGFSMb4cBiF3/gI3bG/hlcUJBNcZPzEYcm20jWG/s3Etjf+YPR5d8vQi+ff9hR3m+ORrxlwSeyEwnPkNjP49ex4kYgtg/bj5gv4z6/TVuyf7hcXPkMEfSG4z4rY/ey3JomNUEADoAgYpXHxb2oAEIAgCCoQnH83Jo+mZbX25cTQdsD3D34Oo0D8MOdfgZOMwSP2WPKuSW5fX1vGA3gmOcLHP82mqteRne5/tqkR8B5mXBPkmc9QX71wmIQkykDvljfrAM6SF+NmsIV6SGT4Bi7tfZjhS+lw0KGTTVHr13qA4IJ/hpHqnaOJt2S5WyxzbLGe2SWusiGLJjJyFQmWgoVFWfC4LPaPCooGm9Wc7oHMvqW6SWiC89pnDODBTKZVLpDG0gimh1go9VadZDj6WIZ4/UCuPgpxSeGGd87MVyBCBnAUQ/hZyyvP7Mm00s+VZlSVkJoWranYl3VoodL73RSTprXo7EYklgZ5Zzc+Kmn5Q4FC1FqYi36j7KpErxx5Qsv07OPQvO8jmWbv5EjnOHouNWYCXnUmTS/0rB+SyJxfq5H8trReMKflmRT07ISrf5Wklshm3zieXNc5df0UiZUyoH3d72/xHtJlLwiKKtOextbvbqZd889u4//lb8CZ2u3ta/QUPvAAAAAElFTkSuQmCC
    mediatype: image/png
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - quota.openshift.io
          resources:
          - clusterresourcequotas/status
          verbs:
          - update
          - patch
        - apiGroups:
          - ""
          resources:
          - namespaces
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - ""
          resources:
          - resourcequotas
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - secrets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - quota.openshift.io
          resources:
          - clusterresourcequotas
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - s3.snappcloud.io
          resources:
          - s3buckets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - s3.snappcloud.io
          resources:
          - s3buckets/finalizers
          verbs:
          - update
        - apiGroups:
          - s3.snappcloud.io
          resources:
          - s3buckets/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - s3.snappcloud.io
          resources:
          - s3userclaims
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - s3.snappcloud.io
          resources:
          - s3userclaims/finalizers
          verbs:
          - update
        - apiGroups:
          - s3.snappcloud.io
          resources:
          - s3userclaims/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - s3.snappcloud.io
          resources:
          - s3users
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - s3.snappcloud.io
          resources:
          - s3users/finalizers
          verbs:
          - update
        - apiGroups:
          - s3.snappcloud.io
          resources:
          - s3users/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        - apiGroups:
          - ""
          resources:
          - resourcequotas/status
          verbs:
          - update
          - patch
        serviceAccountName: ceph-s3-operator-controller-manager
      deployments:
      - label:
          app.kubernetes.io/component: manager
          app.kubernetes.io/created-by: ceph-s3-operator
          app.kubernetes.io/instance: controller-manager
          app.kubernetes.io/managed-by: kustomize
          app.kubernetes.io/name: deployment
          app.kubernetes.io/part-of: ceph-s3-operator
          control-plane: controller-manager
        name: ceph-s3-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                control-plane: controller-manager
            spec:
              affinity:
                nodeAffinity:
                  requiredDuringSchedulingIgnoredDuringExecution:
                    nodeSelectorTerms:
                    - matchExpressions:
                      - key: kubernetes.io/arch
                        operator: In
                        values:
                        - amd64
                        - arm64
                        - ppc64le
                        - s390x
                      - key: kubernetes.io/os
                        operator: In
                        values:
                        - linux
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=0
                image: gcr.io/kubebuilder/kube-rbac-proxy:v0.13.1
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                  protocol: TCP
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 5m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              - args:
                - --config=/ceph-s3-operator/config/config.yaml
                - --health-probe-bind-address=:8081
                - --metrics-bind-address=127.0.0.1:8080
                - --leader-elect
                command:
                - /manager
                image: ghcr.io/snapp-incubator/ceph-s3-operator:v0.3.6
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                ports:
                - containerPort: 9443
                  name: webhook-server
                  protocol: TCP
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 10m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
                volumeMounts:
                - mountPath: /tmp/k8s-webhook-server/serving-certs
                  name: cert
                  readOnly: true
                - mountPath: /ceph-s3-operator/config/
                  name: config
              securityContext:
                runAsNonRoot: true
              serviceAccountName: ceph-s3-operator-controller-manager
              terminationGracePeriodSeconds: 10
              volumes:
              - name: cert
                secret:
                  defaultMode: 420
                  secretName: webhook-server-cert
              - name: config
                secret:
                  items:
                  - key: config.yaml
                    path: config.yaml
                  secretName: ceph-s3-operator-controller-manager-config
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: ceph-s3-operator-controller-manager
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: true
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - s3
  - ceph
  links:
  - name: Documentation
    url: https://github.com/snapp-incubator/ceph-s3-operator/wiki
  maintainers:
  - email: cloud-platform@snapp.cab
    name: Snappcloud Platform Tea
  maturity: stable
  minKubeVersion: 1.23.0
  provider:
    name: Snappcloud
    url: https://github.com/snapp-incubator
  version: 0.3.6
  webhookdefinitions:
  - admissionReviewVersions:
    - v1
    containerPort: 443
    deploymentName: ceph-s3-operator-controller-manager
    failurePolicy: Fail
    generateName: vs3bucket.kb.io
    rules:
    - apiGroups:
      - s3.snappcloud.io
      apiVersions:
      - v1alpha1
      operations:
      - CREATE
      - UPDATE
      resources:
      - s3buckets
    sideEffects: None
    targetPort: 9443
    type: ValidatingAdmissionWebhook
    webhookPath: /validate-s3-snappcloud-io-v1alpha1-s3bucket
  - admissionReviewVersions:
    - v1
    containerPort: 443
    deploymentName: ceph-s3-operator-controller-manager
    failurePolicy: Fail
    generateName: vs3userclaim.kb.io
    rules:
    - apiGroups:
      - s3.snappcloud.io
      apiVersions:
      - v1alpha1
      operations:
      - CREATE
      - UPDATE
      - DELETE
      resources:
      - s3userclaims
    sideEffects: None
    targetPort: 9443
    type: ValidatingAdmissionWebhook
    webhookPath: /validate-s3-snappcloud-io-v1alpha1-s3userclaim
