apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: ack-keyspaces-writer
rules:
- apiGroups:
  - keyspaces.services.k8s.aws
  resources:
  - keyspaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - keyspaces.services.k8s.aws
  resources:
  - keyspaces
  verbs:
  - get
  - patch
  - update
